### PR TITLE
[Avatar addition] Winged Ashera Dragoncat, Nox Wyvern

### PR DESCRIPTION
**Pull request by micksam7**
Avatars are edits to the following bases:

https://takomalynx.itch.io/ashera-dragoncat-vrc-avatar
https://fluffrali.gumroad.com/l/Noxdragon

Note the name added to 'contributor' has unicode in it, which may or may not cause issues.

### CODE REVIEW

**Comment by Happyrobot33** [comment]
dont need to close it
just push to the same branch

**Comment by Happyrobot33** [comment]
also, you mentioned unicode in the contributer, what character is it because that looks like normal ascii?

**Comment by micksam7** [comment]
My bad. And the character is the 'і' U+0456

**Comment by Happyrobot33** [comment]
have you ensured that the 3 hashes provided do not match the base avatars they are edits of? Just want to check

**Comment by micksam7** [comment]
They do not. Arm lengths were changed on the dragoncat until hashes no longer matched, Nox Wyvern has completely new arms and does not match the base.

**Pull request merged**
