### PR TITLE
Add Aviosaur Avatar

### PR DESCRIPTION
**Pull request by fundale**

### CODE REVIEW

**Comment by Happyrobot33** [comment]
Need to fix the date and now the version given i just accepted a PR, and information on where the avatar comes from needs to be included aswell

**Comment by fundale** [comment]
> Need to fix the date and now the version given i just accepted a PR, and information on where the avatar comes from needs to be included aswell

Can you elaborate on info for where the Avatar comes from?
It's listed as made by Furality, and submitted by Orca, unless you're looking for a mention that it was modified?

**Comment by Happyrobot33** [comment]
> > Need to fix the date and now the version given i just accepted a PR, and information on where the avatar comes from needs to be included aswell
> 
> Can you elaborate on info for where the Avatar comes from? It's listed as made by Furality, and submitted by Orca, unless you're looking for a mention that it was modified?

Specifically on like how to get it or a link to it

**Comment by fundale** [comment]
> > > Need to fix the date and now the version given i just accepted a PR, and information on where the avatar comes from needs to be included aswell
> > 
> > 
> > Can you elaborate on info for where the Avatar comes from? It's listed as made by Furality, and submitted by Orca, unless you're looking for a mention that it was modified?
> 
> Specifically on like how to get it or a link to it

Well, Unfortunately you can't get the source files unless you are a Furality Sylva First Class User, or use a Public version uploaded by such people, I can add a referrer to people that do have that to contact Orca, but otherwise can't link to the original source files...

**Comment by jennytoo** [comment]
> Can you elaborate on info for where the Avatar comes from? It's listed as made by Furality, and submitted by Orca, unless you're looking for a mention that it was modified?

Since it's a public, I'd provide as much info as possible generally

Though looking at my previous logs, I've done it as _Name_ by _Author_

In this case, **_Name_ by _Creator_, original model by Furality (link to vrc avatar page)** would be reasonable (IMO)

**Comment by Happyrobot33** [comment]
> > > > Need to fix the date and now the version given i just accepted a PR, and information on where the avatar comes from needs to be included aswell
> > > 
> > > 
> > > Can you elaborate on info for where the Avatar comes from? It's listed as made by Furality, and submitted by Orca, unless you're looking for a mention that it was modified?
> > 
> > 
> > Specifically on like how to get it or a link to it
> 
> Well, Unfortunately you can't get the source files unless you are a Furality Sylva First Class User, or use a Public version uploaded by such people, I can add a referrer to people that do have that to contact Orca, but otherwise can't link to the original source files...
> 
> Also where would I put the referrer for that? I don't see a dedicated space in the Json for that...

This info is enough, the PR just needed some form of source information. It doesnt go into the json but this allows us to git blame for this PR if we ever need to do a hash version update

**Comment by Happyrobot33** [comment]
not sure why the date check is failing....

**Comment by jennytoo** [comment]
> not sure why the date check is failing....

Should be 2014-01-04

**Pull request merged**
