### PR TITLE
Add Darizard Custom Avatar

### PR DESCRIPTION
**Pull request by darizard**
Another avatar for the wing pile :)

### CODE REVIEW

**Comment by mackandelius** [comment]
For procedure's sake, would be good to have a screenshot of the avatar.

While it will break in the future, for short term screenshot sharing, just upload to Discord and share that link.

**Review by Happyrobot33 — CHANGES_REQUESTED** [review]
Just need a picture of the avatar for documentations sake, you can actually paste a image directly in github comment sections and it will embed it directly with a github link

**Comment by jennytoo** [comment]
Is this a modification of a standard (non-flying) base, and if so, has the armature been changed sufficiently for it to produce a different hash?

If this is a custom you are making publicly available I (personally) like to include information on how to get it in the PR. (link to store, discord info, etc), or even a link to the public on VRC. This isn't just a nicety though.

**Comment by darizard** [comment]
@jennytoo This is a modification of Morghus's Nardovern edit of the Nardoragon base by Nardoiri. OpenFlight no longer detects my avatar as a Nardovern due to the changes I made to the dimensions of the Neck and Head bones to achieve a longer neck. This is a personal avatar and at this time I do not plan to make it public.

@mackandelius @Happyrobot33 No problem! Here ya go.

darizardOF

**Review by Happyrobot33 — APPROVED** [review]

**Pull request merged**
