### PR TITLE
[Avatar Addition] Mantled Vern

### PR DESCRIPTION
**Pull request by InvertedCrink**
VRChat_2024-09-21_23-14-26 445_1920x1080

### CODE REVIEW

**Comment by Happyrobot33** [comment]
Is this available anywhere? If so, the link/info would be appreciated for where to find it

**Comment by Happyrobot33** [comment]
I would also be interested in knowing if you have teated with the un edited version of this avatar base to ensure that the hashes are different

**Comment by InvertedCrink** [comment]
its not available anywhere (yet); i made this edit like 3 days ago lol
Unfortunately, (unlike the snogodal vern) his avatar didnt work already
VRChat_2024-09-21_23-15-16 190_1080x1920

**Comment by Happyrobot33** [comment]
> its not available anywhere (yet); i made this edit like 3 days ago lol Unfortunately, (unlike the snogodal vern) his avatar didnt work already VRChat_2024-09-21_23-15-16 190_1080x1920

ill merge this if you post the hash of the original base mantled beast used for this edit, just want to make sure we arent merging in that hash

**Comment by InvertedCrink** [comment]
Ah apologies, i misunderstood what you were asking about; Here is the hash for the public version of the mantled beast available in "Nico & JHK Mantled Beast Avatars".
image
It appears to be different from my hash (which makes sense; i messed with the arm and shoulder positions).

**Pull request merged**
