### PR TITLE
ADD: Durgarra and Wyvernarra

### PR DESCRIPTION
**Pull request by DarkSpirit019**
Adding Support for the Durgarra and Wyvernarra VRChat Avatars. Both can be found on the same Gumroad Page: https://kyderra.gumroad.com/l/Urawr?layout=profile

### CODE REVIEW

**Comment by DarkSpirit019** [comment]
I increased the Minor Version by 2, as they are technically two Different Avatars. Is that Ok, or should i only increase by 1?

**Comment by DarkSpirit019** [comment]
Also for additional Documentation the Gumroad Link to the Avi: https://kyderra.gumroad.com/l/Urawr?layout=profile

**Comment by Happyrobot33** [comment]
> I increased the Minor Version by 2, as they are technically two Different Avatars. Is that Ok, or should i only increase by 1?

In this case the minor version should just be bumped by 1 since your doing it in one PR

**Comment by DarkSpirit019** [comment]
Ok, just did that

**Comment by Happyrobot33** [comment]
Patch field needs to be 0 since you bumped minor

**Comment by DarkSpirit019** [comment]
Reverted it to 0

**Pull request merged**
